### ISSUE TITLE
niveau 4

### ISSUE THREAD

**Issue by lesaint** [fbiville/annotation-processing-ftw#22]
## talk

pas de talk, si déjà certains participants arrivent à ce niveau là durant la session, il y aura probablement trop de monde à des endroits différents du hands-on pour avoir l'attention de la salle

## exercices

* [ ] exo 1 : passer des options au processor
    * sujet possible : forker l'exo 1 du niveau 3 (erreur de compilation si un champs est annoté avec `@Inject`) pour qu'en fonction d'une option, on lève une erreur de compilation ou seulement des warnings
    * il serait intéressant de faire comme au niveau 1, avec d'abord une étape pour voir les options `javac` en ligne de commande, puis trouver comment passer les options dans maven (via le `pom.xml` **et** via la ligne de commande)
* [ ] exo 2 : exercice sur les intéractions entre les AP
* [ ] exo 3 : retourner "*" comme valeur de `getSupportedAnnotationTypes`
* ...

**Comment by fbiville** [comment]
Déscopé.
